In [1]:
import matplotlib.pyplot as plt
import torch
import cv2 as cv

In [2]:
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)

Using cache found in C:\Users\enesa/.cache\torch\hub\ultralytics_yolov5_master
YOLOv5  2022-11-24 Python-3.10.5 torch-1.12.0 CUDA:0 (NVIDIA GeForce GTX 1650 Ti, 4096MiB)

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape... 


In [3]:
classes = model.names
for names in classes.values():
    print(names)

person
bicycle
car
motorcycle
airplane
bus
train
truck
boat
traffic light
fire hydrant
stop sign
parking meter
bench
bird
cat
dog
horse
sheep
cow
elephant
bear
zebra
giraffe
backpack
umbrella
handbag
tie
suitcase
frisbee
skis
snowboard
sports ball
kite
baseball bat
baseball glove
skateboard
surfboard
tennis racket
bottle
wine glass
cup
fork
knife
spoon
bowl
banana
apple
sandwich
orange
broccoli
carrot
hot dog
pizza
donut
cake
chair
couch
potted plant
bed
dining table
toilet
tv
laptop
mouse
remote
keyboard
cell phone
microwave
oven
toaster
sink
refrigerator
book
clock
vase
scissors
teddy bear
hair drier
toothbrush


In [4]:
device = 'cuda'
#device = 'cpu'

In [5]:
image = cv.imread("test_image_1.jpeg")

In [6]:
# modeli oluşturuyoruz
model.to(device)

AutoShape(
  (model): DetectMultiBackend(
    (model): DetectionModel(
      (model): Sequential(
        (0): Conv(
          (conv): Conv2d(3, 32, kernel_size=(6, 6), stride=(2, 2), padding=(2, 2))
          (act): SiLU(inplace=True)
        )
        (1): Conv(
          (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
          (act): SiLU(inplace=True)
        )
        (2): C3(
          (cv1): Conv(
            (conv): Conv2d(64, 32, kernel_size=(1, 1), stride=(1, 1))
            (act): SiLU(inplace=True)
          )
          (cv2): Conv(
            (conv): Conv2d(64, 32, kernel_size=(1, 1), stride=(1, 1))
            (act): SiLU(inplace=True)
          )
          (cv3): Conv(
            (conv): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
            (act): SiLU(inplace=True)
          )
          (m): Sequential(
            (0): Bottleneck(
              (cv1): Conv(
                (conv): Conv2d(32, 32, kernel_size=(1, 1), stride=(1, 1))
  

In [7]:
results = model(image)
print(results)

image 1/1: 667x1000 6 cars, 1 traffic light
Speed: 3.0ms pre-process, 688.2ms inference, 4.0ms NMS per image at shape (1, 3, 448, 640)


In [8]:
print(results.xyxy)

[tensor([[2.84584e+02, 4.47306e+02, 4.05061e+02, 5.31774e+02, 9.23224e-01, 2.00000e+00],
        [8.89566e+01, 4.33869e+02, 2.86444e+02, 5.74758e+02, 9.22351e-01, 2.00000e+00],
        [5.87735e+02, 4.44806e+02, 6.17071e+02, 4.66548e+02, 7.33097e-01, 2.00000e+00],
        [4.02212e+02, 4.25034e+02, 4.96012e+02, 5.06089e+02, 6.93972e-01, 2.00000e+00],
        [6.39535e+02, 4.51794e+02, 6.67238e+02, 4.68053e+02, 6.32966e-01, 2.00000e+00],
        [6.16622e+02, 4.52753e+02, 6.37201e+02, 4.67346e+02, 2.74041e-01, 2.00000e+00],
        [6.54152e+02, 4.02991e+02, 6.62913e+02, 4.16806e+02, 2.51600e-01, 9.00000e+00]], device='cuda:0')]


In [9]:
print(results.xyxy[0])

tensor([[2.84584e+02, 4.47306e+02, 4.05061e+02, 5.31774e+02, 9.23224e-01, 2.00000e+00],
        [8.89566e+01, 4.33869e+02, 2.86444e+02, 5.74758e+02, 9.22351e-01, 2.00000e+00],
        [5.87735e+02, 4.44806e+02, 6.17071e+02, 4.66548e+02, 7.33097e-01, 2.00000e+00],
        [4.02212e+02, 4.25034e+02, 4.96012e+02, 5.06089e+02, 6.93972e-01, 2.00000e+00],
        [6.39535e+02, 4.51794e+02, 6.67238e+02, 4.68053e+02, 6.32966e-01, 2.00000e+00],
        [6.16622e+02, 4.52753e+02, 6.37201e+02, 4.67346e+02, 2.74041e-01, 2.00000e+00],
        [6.54152e+02, 4.02991e+02, 6.62913e+02, 4.16806e+02, 2.51600e-01, 9.00000e+00]], device='cuda:0')


In [10]:
print(results.xyxy[1])

IndexError: list index out of range

In [11]:
print(results.xyxyn)

[tensor([[0.28458, 0.67062, 0.40506, 0.79726, 0.92322, 2.00000],
        [0.08896, 0.65048, 0.28644, 0.86171, 0.92235, 2.00000],
        [0.58773, 0.66688, 0.61707, 0.69947, 0.73310, 2.00000],
        [0.40221, 0.63723, 0.49601, 0.75875, 0.69397, 2.00000],
        [0.63954, 0.67735, 0.66724, 0.70173, 0.63297, 2.00000],
        [0.61662, 0.67879, 0.63720, 0.70067, 0.27404, 2.00000],
        [0.65415, 0.60419, 0.66291, 0.62490, 0.25160, 9.00000]], device='cuda:0')]


In [24]:
print(type(results.xyxyn))

<class 'list'>


In [12]:
print(results.xyxyn[0][:, -1])

tensor([2., 2., 2., 2., 2., 2., 9.], device='cuda:0')


In [13]:
labels, cord = results.xyxyn[0][:, -1], results.xyxyn[0][:, :-1]

In [14]:
print(labels)

tensor([2., 2., 2., 2., 2., 2., 9.], device='cuda:0')


In [15]:
print(cord)

tensor([[0.28458, 0.67062, 0.40506, 0.79726, 0.92322],
        [0.08896, 0.65048, 0.28644, 0.86171, 0.92235],
        [0.58773, 0.66688, 0.61707, 0.69947, 0.73310],
        [0.40221, 0.63723, 0.49601, 0.75875, 0.69397],
        [0.63954, 0.67735, 0.66724, 0.70173, 0.63297],
        [0.61662, 0.67879, 0.63720, 0.70067, 0.27404],
        [0.65415, 0.60419, 0.66291, 0.62490, 0.25160]], device='cuda:0')


In [16]:
n = len(labels) # or len(cord)
print(n)

7


In [17]:
x_shape, y_shape = image.shape[1], image.shape[0]

In [22]:
for i in range(n):
    row = cord[i]
    print(row)
    if row[4] >= 0.5:
        x1, y1, x2, y2 = int(row[0] * x_shape), int(row[1] * y_shape), \
                         int(row[2] * x_shape), int(row[3] * y_shape)

        bgr = (0, 255, 0)
        cv.rectangle(image, (x1, y1), (x2, y2), bgr, 2)

tensor([0.28458, 0.67062, 0.40506, 0.79726, 0.92322], device='cuda:0')
tensor([0.08896, 0.65048, 0.28644, 0.86171, 0.92235], device='cuda:0')
tensor([0.58773, 0.66688, 0.61707, 0.69947, 0.73310], device='cuda:0')
tensor([0.40221, 0.63723, 0.49601, 0.75875, 0.69397], device='cuda:0')
tensor([0.63954, 0.67735, 0.66724, 0.70173, 0.63297], device='cuda:0')
tensor([0.61662, 0.67879, 0.63720, 0.70067, 0.27404], device='cuda:0')
tensor([0.65415, 0.60419, 0.66291, 0.62490, 0.25160], device='cuda:0')


In [23]:
cv.imshow("RESULT", image)
cv.waitKey(0)
cv.destroyAllWindows()